### ISSUE TITLE
Menubar Icon Disappears 

### ISSUE THREAD

**Issue by pqhf5kd** [AnaghSharma/Ambar-SwiftUI#1]
Thank you for the template. Why does the menubar icon disappear while the mouse button is held?

**Comment by AnaghSharma** [comment]
Glad to know that you liked this project. I don't know how but I think the reason behind that is the way `statusItem` is being initialized. If you initialize the `statusItem` in `StatusBarController.swift` using `NSStatusBar.system`, you shouldn't be having this problem. I hope this helps.

**Comment by AnaghSharma** [comment]
@pqhf5kd Did you try what I suggested? Else I am going to close this issue.

**Comment by pqhf5kd** [comment]
@AnaghSharma sorry, I haven't. My project stopped running for some reason and now even when I run a fresh copy of the example, I get an EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0) error.

**Comment by AnaghSharma** [comment]
@pqhf5kd This kind of error is kinda hard to diagnose I think. If you are able to test the above solution, let me know if it works or reopen the issue otherwise, since I am closing it for now. Thanks.
