### ISSUE TITLE
Popover is not showing

### ISSUE THREAD

**Issue by giacomorebonato** [AnaghSharma/Ambar-SwiftUI#2]
Hi, I came on this repo after I read your nice blog post.
I followed all the instructions, but the popover is not showing.
I checked out this repo then to try it... and I can't see the popover after click on this one too.

I saw this [Reddit thread](https://www.reddit.com/r/SwiftUI/comments/e21m7q/a_macos_menu_bar_app_built_with_swiftui/) and comment by somebody suggesting to change: 

```swift
statusItem = NSStatusBar.system.statusItem(withLength: NSStatusItem.squareLength)
```

But even with this change the click is not triggering the action for me.

**Comment by giacomorebonato** [comment]
OK, it breaks because my menubar is set to auto hide.
How can the solution be adapted to work in this case too?

**Comment by AnaghSharma** [comment]
Thanks for pointing this out. Interesting problem. I think it's kinda hard to diagnose, but I'll give it a try.

**Comment by giacomorebonato** [comment]
I have found a solution. I'll share it soon :)

**Comment by AnaghSharma** [comment]
Awesome. Share once done. I'll close the issue post that.

**Comment by tmm** [comment]
@giacomorebonato any chance you can share the solution?

**Comment by AnaghSharma** [comment]
@giacomorebonato Since you've found the solution, I'll close the issue now. Thanks.
