### ISSUE TITLE
No AppDelegate in newer Xcode projects

### ISSUE THREAD

**Issue by ghost** [AnaghSharma/Ambar-SwiftUI#3]
In Xcode 12.2, creating a new SwiftUI macOS App results in a main file that looks different than the `AppDelegate.swift` of this repo.

`MyApp.swift`:

```swift
import SwiftUI

@main
struct MyApp: App {
    var body: some Scene {
        WindowGroup {
            ContentView()
        }
    }
}
```

Would it be possible to update your example for this new structure?
Thanks!

**Comment by AnaghSharma** [comment]
Hi @vbersier, thanks for the feedback. I will definitely try and see what can be done in this situation.

**Comment by alexmodrono** [comment]
@vbersier if you're in need of a solution right now, try this repo: https://github.com/zaferarican/menubarpopoverswiftui2.

It provides an example of a menubar app in the new SwiftUI App Lifecycle

**Comment by ghost** [comment]
@iAlex11 Your project "menubarpopoverswiftui2" throws a bunch of errors of the final release of BigSur/XCode 12. Doesn't look like it's the code, but perhaps the project settings? I've managed to get it to build by starting a new project and importing the code into that.

**Comment by alexmodrono** [comment]
Hi @matt-watkins-1976, it is not my project tho 😅

Yeah, I know what you're talking about. It is because the project was made in the Big Sur beta, which was codenamed as macOS 10.16, but the final release of Big Sur changed it to macOS 11, so the project is configured for macOS 10.16, which is a version that doesn't exist, and that's the reason why Xcode complains about `x` method only being available in macOS 11 or newer.

**Comment by alexmodrono** [comment]
changing the version number from 10.16 to 11 should do the trick

**Comment by ghost** [comment]
@iAlex11 Point taken - hopefully the owner will update it... It is a useful example, though. And yeah, those are exactly the errors I got... I did try bumping the version in the project, but Xcode still complained.

**Comment by beeb** [comment]
Thanks for the help guys. @iAlex11 using an `NSApplicationDelegateAdaptor` is exactly what I ended up doing in the meantime. Makes it a little bit harder to get my head around that new SwiftUI thing since it's a mix of AppKit and SwiftUI but it works.

**Comment by ghost** [comment]
Oops posted that reply with the wrong account ^-^
Since I wanted to move to a MVVM structure, I'm still trying to see how I can observe the ViewModel instance (`ObservableObject` protocol) inside the `StatusBarController` to update the button's icon according to some state variable. For now, I'm relying on `UserDefaults` which I can observe.

**Comment by alexmodrono** [comment]
Glad it helped!

**Comment by zaferarican** [comment]
Hi, I am the owner of [https://github.com/zaferarican/menubarpopoverswiftui2](https://github.com/zaferarican/menubarpopoverswiftui2). 

The latest commit should fix the wrong deployment target (Without knowing the issue though). Thanks @iAlex11 for pointing to the repo.

Feel free to open an issue for any questions or problems.

**Comment by AnaghSharma** [comment]
Looks like everything is fine now. Will close the issue now.
